name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # Install latest CMake.
    - uses: lukka/get-cmake@latest

    - name: cmake version
      run: cmake --version
    - name: cmake list presets
      run: cmake --list-presets