name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: cmake version
      run: cmake --version
    - name: cmake list presets
      run: cmake --list-presets